// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi_money_management.Data;

#nullable disable

namespace WebApi_money_management.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612230306_AddBanksAndCategories")]
    partial class AddBanksAndCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi_money_management.Entities.Bank", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = "BT",
                            Name = "Banca Transilvania"
                        },
                        new
                        {
                            Id = "ING",
                            Name = "ING Bank"
                        },
                        new
                        {
                            Id = "BCR",
                            Name = "BCR"
                        },
                        new
                        {
                            Id = "BRD",
                            Name = "BRD"
                        },
                        new
                        {
                            Id = "Raiffeisen",
                            Name = "Raiffeisen Bank"
                        },
                        new
                        {
                            Id = "UniCredit",
                            Name = "UniCredit Bank"
                        },
                        new
                        {
                            Id = "CEC",
                            Name = "CEC Bank"
                        },
                        new
                        {
                            Id = "Other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("WebApi_money_management.Entities.BankStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BankStatements");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salary",
                            Type = "income"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Freelance",
                            Type = "income"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Business",
                            Type = "income"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Investment",
                            Type = "income"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gift",
                            Type = "income"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Refund",
                            Type = "income"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other",
                            Type = "income"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Food & Drink",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Transport",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Utilities",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Health",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Shopping",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Entertainment",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Housing",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Education",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Other",
                            Type = "expense"
                        });
                });

            modelBuilder.Entity("WebApi_money_management.Entities.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("light");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.BankStatement", b =>
                {
                    b.HasOne("WebApi_money_management.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.Transaction", b =>
                {
                    b.HasOne("WebApi_money_management.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi_money_management.Entities.UserPreference", b =>
                {
                    b.HasOne("WebApi_money_management.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WebApi_money_management.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
